// flow-typed signature: 913c803884af89a77999a61dad230081
// flow-typed version: <<STUB>>/lodash.clonedeep_v4.5.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.clonedeep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.clonedeep' {
  declare export default <T>(obj: T) => T;
}
