// flow-typed signature: 6e6061d3a0a326f4f7e404264ad71010
// flow-typed version: <<STUB>>/react-apollo_v^1.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-apollo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-apollo' {
  declare module.exports: any;
}
