// flow-typed signature: 7e5e2d4ca5b8eff7561b6ac4d514a7bb
// flow-typed version: <<STUB>>/react-typeahead_v^2.0.0-alpha.5/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-typeahead'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-typeahead' {
  declare module.exports: any;
}