// flow-typed signature: 0246ad48b2ed8ac25e739ac89d688ddc
// flow-typed version: <<STUB>>/semantic-ui-react_v0.68.5/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semantic-ui-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semantic-ui-react' {
  declare module.exports: any;
}
