// flow-typed signature: 2b180d085446c99ed609cd530c7424e0
// flow-typed version: <<STUB>>/@storybook/react_v3.1.7/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/react/addons' {
  declare module.exports: any;
}

